47 notification per email als erinnerung
thiws24/equipli pull request #65
Opened 2024-11-10 19:46 UTC by Ainges

2024-11-18 10:35 UTC, d135-1r43 requested changes
Bitte noch n Test der das korrekte Generieren des HTMLs aus dem Template testet.

2024-11-19 09:05 UTC, d135-1r43 approved these changes

2024-11-19 09:20 UTC, Ainges commented
Die Benennung wurde noch angepasst. Sorry da war ich gestern wohl zu voreilig mit dem Review-Request.

2024-11-26 07:56 UTC, d135-1r43 requested changes
Achte bitte drauf, dass du nicht unnötige leere Zeilen machst. Leere Zeilen sind nur zum Strukturieren des Codes da.

2024-11-26 07:56 UTC, d135-1r43 commented on backend/mailservice/src/main/java/de/equipli/processors/keycloak/GetUserDataFromKeycloakProcessor.java
> +                "secret"                      // Client Secret
Bitte hier Konfigurationen verwenden.

2024-11-26 07:56 UTC, d135-1r43 commented on backend/mailservice/src/main/java/de/equipli/processors/keycloak/GetUserDataFromKeycloakProcessor.java
> +
Whitespace löschen.

2024-11-26 07:56 UTC, d135-1r43 commented on backend/mailservice/src/main/java/de/equipli/processors/mail/CollectMailProcessor.java
> +
Whitespace löschen

2024-11-26 07:56 UTC, d135-1r43 commented on backend/mailservice/src/main/java/de/equipli/restclient/inventoryservice/InventoryService.java
> +
Whitespace löschen

2024-11-26 11:44 UTC, Ainges commented
Zur Info: 
Der Service funktioniert lokal korrekt. 

Das deployment scheitert aktuell noch an
- resend: Gleicher Fehler wie in #47 beschrieben
- Keycloak auf id.equipli.de. Trotz (augenscheinlich) gleicher Config können die Daten über den User nicht abgefragt werden
![image](https://github.com/user-attachments/assets/c47944dc-45c3-4493-befa-6f8d4c22f6db)

2024-11-26 17:52 UTC, Ainges commented on backend/mailservice/src/main/java/de/equipli/processors/keycloak/GetUserDataFromKeycloakProcessor.java
> -        UserResource userResource = keycloak.realm("quarkus")
Das Deployment ist peinlicherweise tatsächlich nur daran gescheitert...
Fixed! ✅

2024-12-05 13:31 UTC, d135-1r43 approved these changes

2024-12-05 13:31 UTC, d135-1r43 commented
Soll ich mergen?

2024-12-05 13:35 UTC, Ainges commented
Nein bitte noch nicht. Ich muss noch die Array Verarbeitung implementieren. Ich werde den PR dann von Draft auf Open stellen.

2024-12-08 21:43 UTC, Ainges commented
Ready for Review. 
Tests folgen Morgen.

2024-12-09 08:40 UTC, d135-1r43 approved these changes

2024-12-09 08:40 UTC, merged